/*
 * WAV Library Phase 3 Test - MSX Bit Encoding (FSK)
 * =================================================
 * 
 * What this phase implements:
 * - FSK (Frequency Shift Keying) encoding for MSX cassette format
 * - writeBit0() - generates 1 pulse at 1200 Hz (one complete cycle)
 * - writeBit1() - generates 2 pulses at 2400 Hz (two complete cycles)
 * - MSX-compatible binary data encoding
 * 
 * What this test does:
 * - Creates alternating 0/1 bit patterns for frequency verification
 * - Tests byte-level bit patterns (all combinations)
 * - Generates long sequences of each bit type for timing verification
 * - Validates that 0-bits take ~0.833ms and 1-bits take ~0.833ms
 * - Produces WAV files that can be analyzed with audio spectrum tools
 * - Verifies LSB-first bit ordering (MSX serial protocol)
 */

#include "lib/wavlib.h"
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    WavFormat format = createDefaultWavFormat();
    WaveformConfig waveform = createDefaultWaveform();
    
    // Test 1: Generate alternating 0s and 1s pattern (10 of each)
    printf("Creating test_bits_pattern.wav...\n");
    WavWriter *writer = createWavFile("test_bits_pattern.wav", &format);
    if (!writer) {
        fprintf(stderr, "Failed to create test_bits_pattern.wav\n");
        return 1;
    }
    
    // Write 100ms silence (header lead-in)
    writeSilence(writer, 0.1);
    
    // Write alternating pattern: 0, 1, 0, 1, 0, 1...
    for (int i = 0; i < 10; i++) {
        if (!writeBit0(writer, &waveform)) {
            fprintf(stderr, "Failed to write bit 0\n");
            closeWavFile(writer);
            return 1;
        }
        if (!writeBit1(writer, &waveform)) {
            fprintf(stderr, "Failed to write bit 1\n");
            closeWavFile(writer);
            return 1;
        }
    }
    
    // Write 100ms silence (trailer)
    writeSilence(writer, 0.1);
    
    if (!closeWavFile(writer)) {
        fprintf(stderr, "Failed to close test_bits_pattern.wav\n");
        return 1;
    }
    printf("  ✓ Generated alternating bit pattern (10 zeros, 10 ones)\n");
    
    // Test 2: Generate a byte pattern (all combinations)
    printf("\nCreating test_bits_byte.wav...\n");
    writer = createWavFile("test_bits_byte.wav", &format);
    if (!writer) {
        fprintf(stderr, "Failed to create test_bits_byte.wav\n");
        return 1;
    }
    
    writeSilence(writer, 0.1);
    
    // Write the byte 0xA5 = 10100101 in LSB-first order
    // LSB-first: 1, 0, 1, 0, 0, 1, 0, 1
    uint8_t test_byte = 0xA5;
    printf("  Writing byte 0x%02X (LSB-first):\n    ", test_byte);
    for (int bit = 0; bit < 8; bit++) {
        int bit_value = (test_byte >> bit) & 1;
        printf("%d", bit_value);
        
        if (bit_value) {
            if (!writeBit1(writer, &waveform)) {
                fprintf(stderr, "\nFailed to write bit 1\n");
                closeWavFile(writer);
                return 1;
            }
        } else {
            if (!writeBit0(writer, &waveform)) {
                fprintf(stderr, "\nFailed to write bit 0\n");
                closeWavFile(writer);
                return 1;
            }
        }
    }
    printf("\n");
    
    writeSilence(writer, 0.1);
    
    if (!closeWavFile(writer)) {
        fprintf(stderr, "Failed to close test_bits_byte.wav\n");
        return 1;
    }
    printf("  ✓ Generated byte pattern (0xA5 in LSB-first order)\n");
    
    // Test 3: Long sequence of zeros (tests 1200 Hz stability)
    printf("\nCreating test_bits_zeros.wav...\n");
    writer = createWavFile("test_bits_zeros.wav", &format);
    if (!writer) {
        fprintf(stderr, "Failed to create test_bits_zeros.wav\n");
        return 1;
    }
    
    writeSilence(writer, 0.05);
    
    // Write 100 zeros
    for (int i = 0; i < 100; i++) {
        if (!writeBit0(writer, &waveform)) {
            fprintf(stderr, "Failed to write bit 0\n");
            closeWavFile(writer);
            return 1;
        }
    }
    
    writeSilence(writer, 0.05);
    
    if (!closeWavFile(writer)) {
        fprintf(stderr, "Failed to close test_bits_zeros.wav\n");
        return 1;
    }
    printf("  ✓ Generated 100 zero-bits (1200 Hz)\n");
    
    // Test 4: Long sequence of ones (tests 2400 Hz stability)
    printf("\nCreating test_bits_ones.wav...\n");
    writer = createWavFile("test_bits_ones.wav", &format);
    if (!writer) {
        fprintf(stderr, "Failed to create test_bits_ones.wav\n");
        return 1;
    }
    
    writeSilence(writer, 0.05);
    
    // Write 100 ones
    for (int i = 0; i < 100; i++) {
        if (!writeBit1(writer, &waveform)) {
            fprintf(stderr, "Failed to write bit 1\n");
            closeWavFile(writer);
            return 1;
        }
    }
    
    writeSilence(writer, 0.05);
    
    if (!closeWavFile(writer)) {
        fprintf(stderr, "Failed to close test_bits_ones.wav\n");
        return 1;
    }
    printf("  ✓ Generated 100 one-bits (2400 Hz)\n");
    
    // Test 5: Different waveform types (square wave for comparison)
    printf("\nCreating test_bits_square.wav (with square wave)...\n");
    WaveformConfig square = createWaveform(WAVE_SQUARE, 120);
    
    writer = createWavFile("test_bits_square.wav", &format);
    if (!writer) {
        fprintf(stderr, "Failed to create test_bits_square.wav\n");
        return 1;
    }
    
    writeSilence(writer, 0.05);
    
    // Write alternating pattern with square wave
    for (int i = 0; i < 10; i++) {
        writeBit0(writer, &square);
        writeBit1(writer, &square);
    }
    
    writeSilence(writer, 0.05);
    
    if (!closeWavFile(writer)) {
        fprintf(stderr, "Failed to close test_bits_square.wav\n");
        return 1;
    }
    printf("  ✓ Generated alternating bits with square waveform\n");
    
    printf("\n=== Phase 3 Test Complete ===\n");
    printf("Generated files:\n");
    printf("  - test_bits_pattern.wav  (alternating 0/1 pattern)\n");
    printf("  - test_bits_byte.wav     (byte 0xA5 in LSB-first)\n");
    printf("  - test_bits_zeros.wav    (100 zero-bits at 1200 Hz)\n");
    printf("  - test_bits_ones.wav     (100 one-bits at 2400 Hz)\n");
    printf("  - test_bits_square.wav   (alternating with square wave)\n");
    printf("\nTo verify:\n");
    printf("  1. Listen to files - should hear distinct pitch change between 0 and 1\n");
    printf("  2. Analyze in audio software - measure frequencies and timing\n");
    printf("  3. Check file sizes - bits should have consistent timing\n");
    
    return 0;
}
